language: rust
sudo: false
rust:
- stable
- beta
- nightly
script:
- (cd ogg && cargo test --verbose)
- (cd ogg_clock && cargo test --verbose)
- (cd ireul_interface && cargo test --verbose)
- cargo test --verbose
