[package]
name = "ireul_interface"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[dependencies.ogg]
path = "../ogg"

[dependencies.ogg_clock]
path = "../ogg_clock"

[dependencies]
serde = "*"
serde_macros = "*"
bincode = "*"